apiVersion: v1
kind: ReplicationController
metadata:
  name: tf-runner-jupyter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: tf-runner-jupyter
    spec:
      containers:
      - name: tf-runner-jupyter
        image: registry.dataos.io/library/tensorflow:0.8.0
        imagePullPolicy: Always
        ports:  
        - containerPort: 8888
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tf-runner-jupyter
  labels:
    name: tf-runner-jupyter
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888  
  selector:
    name: tf-runner-jupyter
